//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newdevice
    {
        public int Deviceid { get; set; }
        public string Devicename { get; set; }
        public string Temperature { get; set; }
        public string Humidity { get; set; }
    }
}
